name: hazard2csep
channels:
    - conda-forge
    - defaults
dependencies:
    - python = 3.11
    - numpy
    - pycsep
    - openquake.engine
    - pandas
    - geopandas
    - matplotlib
    - cartopy
    - shapely